diskimages:
  - name: centos-7
    elements:
      - centos-minimal
      - vm
      - nodepool
  - name: ubuntu-trusty
    elements:
      - ubuntu-minimal
      - vm
      - nodepool

labels:
  - name: centos-7
    image: centos-7
    min-ready: 1
    providers:
      - name: openstack
  - name: ubuntu-trusty
    image: ubuntu-trusty
    min-ready: 1
    providers:
      - name: openstack

providers:
  - name: openstack
    cloud: openstack
    max-servers: 10
    images:
      - name: centos-7
        min-ram: 8192
        diskimage: centos-7
        private-key: /var/lib/nodepool/.ssh/id_rsa
        username: jenkins
      - name: ubuntu-trusty
        min-ram: 8192
        diskimage: ubuntu-trusty
        private-key: /var/lib/nodepool/.ssh/id_rsa
        username: jenkins

targets:
  - name: jenkins01
